apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observa-spike0
resources:
  - lag-exporter.yaml
  - scaledobjects.yaml
configMapGenerator:
  - name: lag-exporter-script
    files: [lag_exporter.py]
