global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus/rules/rules.yaml
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: collector
    static_configs:
      - targets: ['collector:8888']
  - job_name: probes
    dns_sd_configs:
      - names: ['probe-node.observa-spike0.svc.cluster.local', 'probe-python-sink.observa-spike0.svc.cluster.local']
        type: A
        port: 8000
  - job_name: domain
    dns_sd_configs:
      - names: ['order.observa-spike0.svc.cluster.local', 'payment.observa-spike0.svc.cluster.local', 'inventory.observa-spike0.svc.cluster.local', 'notification.observa-spike0.svc.cluster.local']
        type: A
        port: 8000
  - job_name: consumer-lag
    static_configs:
      - targets: ['lag-exporter.observa-spike0.svc.cluster.local:9108']
